# Generated by Django 3.0.3 on 2020-08-15 13:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('CLOSED', 'closed')], default='PENDING', max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='company_files/pictures')),
                ('banner', models.ImageField(blank=True, upload_to='company_files/banners')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='company.CompanyContacts')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='company.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='company.CompanyContacts')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_files/images')),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company.CompanyFiles')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_files/files')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='company.CompanyFiles')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='company.CompanyContacts')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('short_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.Category')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.CompanyContacts')),
            ],
        ),
    ]
