# Generated by Django 3.0.3 on 2020-08-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200815_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='company.Company'),
        ),
    ]
