# Generated by Django 3.0.4 on 2020-09-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='site',
            field=models.TextField(default=''),
        ),
    ]
