# Generated by Django 3.0.4 on 2020-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyinfo_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='adress',
            field=models.TextField(default=''),
        ),
    ]
