# Generated by Django 3.0.4 on 2020-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companyservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
