# Generated by Django 3.0.4 on 2020-09-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200923_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
