# Generated by Django 3.0.4 on 2020-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
