# Generated by Django 3.0.4 on 2020-09-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20200924_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
