# Generated by Django 3.0.4 on 2020-09-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
