# Generated by Django 3.0.4 on 2020-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
