# Generated by Django 3.0.4 on 2020-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('pk_number', models.IntegerField(default='')),
                ('email', models.TextField(default='')),
                ('review', models.TextField(default='')),
            ],
        ),
    ]
