# Generated by Django 3.0.4 on 2020-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20200928_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='company_fk',
            field=models.IntegerField(default=1),
        ),
    ]
