# Generated by Django 3.0.4 on 2020-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20200928_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.IntegerField(default=1)),
                ('city', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('worktime', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Uslugi',
        ),
    ]
