# Generated by Django 3.0.4 on 2020-09-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20200928_1847'),
        ('company', '0023_news_date'),
    ]

    operations = [
    ]
