# Generated by Django 3.0.3 on 2020-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_merge_20200929_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='search_info',
            field=models.TextField(default=''),
        ),
    ]
