# Generated by Django 3.0.4 on 2020-10-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_companyinfo_search_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='company_services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='company.Company'),
            preserve_default=False,
        ),
    ]
