# Generated by Django 3.0.4 on 2020-10-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_services_company_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='company_services',
        ),
    ]
