# Generated by Django 3.0.4 on 2020-10-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_remove_services_company_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=0)),
                ('timeleft', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompanyTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifes', to='company.Company')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companiees', to='company.Tarif')),
            ],
        ),
    ]
