# Generated by Django 3.0.4 on 2020-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20201006_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='bin',
            field=models.TextField(default=''),
        ),
    ]
