# Generated by Django 3.0.4 on 2020-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='company_files/pictures/Bi-group.png', upload_to='company_files/images'),
        ),
    ]
