# Generated by Django 3.0.4 on 2020-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(default='company_files/pictures/Bi-group.png', upload_to='news_filles/images'),
        ),
    ]
