# Generated by Django 3.0.4 on 2020-10-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_auto_20201026_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='', max_length=50)),
                ('region_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='company.City')),
            ],
        ),
    ]
