# Generated by Django 3.0.4 on 2020-10-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_city',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='company.region'),
            preserve_default=False,
        ),
    ]
