# Generated by Django 3.0.4 on 2020-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='company_files/files'),
        ),
    ]
