# Generated by Django 3.0.4 on 2020-10-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_auto_20201028_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='reBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.IntegerField(default=1)),
                ('city', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('worktime', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='reServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('image', models.ImageField(default='company_files/pictures/Bi-group.png', upload_to='company_files/images')),
            ],
        ),
        migrations.CreateModel(
            name='reImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_files/images')),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_images', to='company.CompanyFiles')),
            ],
        ),
        migrations.CreateModel(
            name='reFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='company_files/files')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_files', to='company.CompanyFiles')),
            ],
        ),
        migrations.CreateModel(
            name='reCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('short_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('region', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('site', models.TextField(default='')),
                ('worktime', models.TextField(default='')),
                ('adress', models.TextField(default='')),
                ('bin', models.TextField(default='')),
                ('search_info', models.TextField(default='')),
                ('fake_id', models.IntegerField(default=0, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_info', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='reCompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_companies', to='company.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_categories', to='company.Company')),
            ],
        ),
    ]
