# Generated by Django 3.0.4 on 2020-10-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_rebranches_recompanycategory_recompanyinfo_refile_reimage_reservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='redactingCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_pk', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
