# Generated by Django 3.0.4 on 2020-10-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_redactingcompanies_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='company.Company')),
            ],
        ),
    ]
