# Generated by Django 3.0.4 on 2020-10-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_companymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='reCompanyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='company_files/pictures')),
                ('banner', models.ImageField(blank=True, upload_to='company_files/banners')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_files', to='company.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='refile',
            name='company_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_files', to='company.reCompanyFiles'),
        ),
        migrations.AlterField(
            model_name='reimage',
            name='company_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_images', to='company.reCompanyFiles'),
        ),
    ]
