# Generated by Django 3.0.4 on 2020-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_companyinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='emailclicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='serviceRequestclicks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
