# Generated by Django 3.0.4 on 2020-10-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_companymembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
