# Generated by Django 3.0.4 on 2020-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_company_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='addressVievClicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phoneViewClicks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
