# Generated by Django 3.0.4 on 2020-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_verificationcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodes',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
