# Generated by Django 3.0.4 on 2020-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_verificationcodes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='company_files/files'),
        ),
    ]
