# Generated by Django 3.0.4 on 2020-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_verificationcodes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
