# Generated by Django 3.0.3 on 2020-09-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0006_invoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charged',
            field=models.BooleanField(default=False),
        ),
    ]
